apiVersion: v1
kind: Pod
metadata:
  name: ecm516-20262-lembretes
spec:
  containers:
    - name: ecm516-20262-lembretes
      image: rodbossini/lembretes:0.0.1
      resources:
        limits:
          memory: 256Mi
          cpu: 1